14-intro-to-rails/new_new_rails_school/config/routes.rb
Rails.application.routes.draw do
  get '/students', to: 'students#index', as: 'students'
  get '/students/:id', to: 'students#show', as: 'student'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

14-intro-to-rails/new_new_rails_school/app/models/student.rb
class Student < ApplicationRecord
end

14-intro-to-rails/new_new_rails_school/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
    render :index
  end

  def show 
    @student = Student.find(params[:id])
  end 
end

14-intro-to-rails/new_new_rails_school/app/helpers/students_helper.rb
module StudentsHelper
end

14-intro-to-rails/new_new_rails_school/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewNewRailsSchool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

14-intro-to-rails/new_new_rails_school/app/views/students/index.html.erb
<h1>Students#index</h1>

<% @students.each do |student| %>
  <p><%= link_to student.name, student_path(student.id) %></p>
<% end %>

14-intro-to-rails/new_new_rails_school/app/views/students/show.html.erb
<h1>Show Page</h1>

<p><%= @student.name %></p>
<p><%= @student.age %></p>
<p><%= @student.grade %></p>

<%= link_to 'INDEX', students_path  %>