19-auth/paddys_puzzles/config/routes.rb
Rails.application.routes.draw do
  resources :user_drinks, only: [:new, :create]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:index, :show, :new, :create]
  resources :drinks
  # resources :drinks, only: [:index, :show, :new, :create, :edit, :update]
  # resources :drinks, except: [:destroy]

  
  # get '/drinks', to: 'drinks#index', as: 'drinks'
  # get '/drinks/new', to: 'drinks#new', as: 'new_drink'
  # get '/drinks/:id', to: 'drinks#show', as: 'drink'

  # post '/drinks', to: 'drinks#create'
  delete '/sessions/reset', to: 'sessions#reset_session', as: 'reset'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions', to: 'sessions#create', as: 'login'
  delete '/session', to: 'sessions#destroy', as: 'logout'
  


end

19-auth/paddys_puzzles/app/models/drink.rb
class Drink < ApplicationRecord
  has_many :user_drinks
  has_many :users, through: :user_drinks

  validates :name, uniqueness: true
  validates :name, :category, presence: true
  validates :category, inclusion: {in: ["beer", "cocktail", "wine"]}
  validates :ounces, numericality: {greater_than_or_equal_to: 6, less_than_or_equal_to: 40}

  validate :name_can_not_be_scott

  def name_can_not_be_scott
    if self.name && self.name.downcase == 'scott'
      self.errors.add(:name, "Can not be Scott")
    end 
  end 



  def rating_average
    total = 0

    self.user_drinks.each do |user_drink|
      total += user_drink.rating
    end 

    if self.user_drinks.length > 0
      total / self.user_drinks.length
    else 
      total
    end 
  end 
end

19-auth/paddys_puzzles/app/models/user.rb
class User < ApplicationRecord
  has_many :user_drinks
  has_many :drinks, through: :user_drinks

  has_secure_password

  # def password=(secret)
  #   byebug
  #   hashed_pass = BCrypt::Password.create(secret)
  #   self.password_digest = hashed_pass
  # end 

  # def password
  # end 

  # def authenticate(secret)
  #   hashed_pass = BCrypt::Password.new(secret)

  #   self.password_digest == hashed_pass 
  # end 
end

19-auth/paddys_puzzles/app/models/user_drink.rb
class UserDrink < ApplicationRecord
  belongs_to :drink
  belongs_to :user
end

19-auth/paddys_puzzles/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user
  before_action :authorized

  def set_user
    @logged_in_user = User.find_by(id: session[:user_id])
  end 

  def authorized
    if @logged_in_user
      # do whatever they were trying to do
    else
      flash[:error] = "Gotta Log In Homie"
      redirect_to new_login_path
    end 
  end
end

19-auth/paddys_puzzles/app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :find_drink, only: [:show, :edit, :update, :destroy]

  def index 
    @drinks = Drink.all
    # render :index
  end 

  def show 
    # cookies[:page_counter] = 1

    # cookies[:page_counter] = cookies[:page_counter].to_i + 1
    session[:page_counter] = session[:page_counter].to_i + 1
    # @drink = Drink.find(params[:id])
  end 

  def new 
    @drink = Drink.new
    # render :new
  end 

  def create
    @drink = Drink.create(drink_params)
    
    # drink = Drink.new(drink_params)
    # drink.save -- returns a boolean

    if @drink.valid?
      flash[:success] = "WELCOME TO THE DRINK LIST FELLOW DRINk"
      redirect_to drink_path(@drink.id)
    else 
      flash[:my_errors] = @drink.errors.full_messages
     
      redirect_to new_drink_path
    end 
  end 

  def edit 
    # @drink = Drink.find(params[:id])
  end 
  
  def update 
    # @drink = Drink.find(params[:id])

    if @drink.update(drink_params)
      redirect_to drink_path(@drink)
    else
      flash[:my_errors] = @drink.errors.full_messages
      redirect_to edit_drink_path(@drink)
    end 
  end 

  def destroy 
    # @drink = Drink.find(params[:id])
    @drink.destroy 

    redirect_to drinks_path
  end 

  private 

  def drink_params
    params.require(:drink).permit(:name, :img_url, :ounces, :category)
  end 

  def find_drink
    @drink = Drink.find(params[:id])
  end 
end

19-auth/paddys_puzzles/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def reset_session
    session[:page_counter] = 0

    redirect_back fallback_location: drinks_path
  end 

  def new
  end

  def create
    user = User.find_by(name: session_params[:name])

    if user && user.authenticate(session_params[:password]) 
      session[:user_id] = user.id 
      redirect_to user
    else 
      flash[:error] = 'Something did not match'
      redirect_to new_login_path
    end 
  end

  def destroy 
    session[:user_id] = nil
    redirect_to drinks_path
  end 
  
  
  private 
  def session_params
    params.require(:session).permit(:name, :password)
  end 
end 

19-auth/paddys_puzzles/app/controllers/user_drinks_controller.rb
class UserDrinksController < ApplicationController

  def new
     @user_drink = UserDrink.new

     @drinks = Drink.all
     @users = User.all
  end 

  def create 
    user_drink = UserDrink.create(user_drink_params)
    
    redirect_to drink_path(user_drink.drink)
  end 

  private 

  def user_drink_params
    params.require(:user_drink).permit(:content, :rating, :user_id, :drink_id)
  end 
end

19-auth/paddys_puzzles/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:create, :new]


  def index 
    @users = User.all
  end 
  
  def show 
    @user = User.find(params[:id])

    if @user == @logged_in_user
      render :show 
    else
      redirect_to users_path 
    end 
  end 

  def new 
    @user = User.new
  end 

  def create 
    user = User.create(user_params)

    if user.valid? 
      session[:user_id] = user.id
      redirect_to user 
    else 
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end
  end 


  private 
  def user_params
    params.require(:user).permit(:name, :image_url, :password)
  end 
end

19-auth/paddys_puzzles/app/helpers/application_helper.rb
module ApplicationHelper
end

19-auth/paddys_puzzles/app/helpers/user_drinks_helper.rb
module UserDrinksHelper
end

19-auth/paddys_puzzles/app/helpers/users_helper.rb
module UsersHelper
end

19-auth/paddys_puzzles/app/views/drinks/_form.html.erb
<% if flash[:my_errors] %>
  <% flash[:my_errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for @drink  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.label :ounces %>
  <%= f.number_field :ounces %>

  <%= f.submit %>
<% end %>

19-auth/paddys_puzzles/app/views/drinks/edit.html.erb
<h1>Edit Drink</h1>

<%= render 'form' %>

19-auth/paddys_puzzles/app/views/drinks/index.html.erb
<h1>Drinks</h1>

<div class="index_container">
  <% @drinks.each do |drink| %>
    <div class="index_tile">
      <h3><%= link_to drink.name, drink_path(drink) %></h3>
      <p><%= drink.category.capitalize %></p>
      <img class="index_img" src="<%= drink.img_url %>" alt="<%= drink.name%>">

      <%= button_to 'Delete Drink', drink_path(drink), method: :delete %>

    </div>
  <% end %>
</div>

19-auth/paddys_puzzles/app/views/drinks/new.html.erb
<h1>New Drink</h1>

<%= render 'form' %>


<%# <form action="/drinks" method="POST">
  <input type="text" name="drink[name]" >
  <input type="text" name="category" >
  <input type="text" name="img_url" >
  <input type="number" name="ounces">

  <input type="submit">
</form> %>

19-auth/paddys_puzzles/app/views/drinks/show.html.erb
<h1>Drink</h1>
<% if session[:page_counter].to_i > 3 %>

  <div>
    <iframe width="764" height="573" src="https://www.youtube.com/embed/tHQufUqtWcc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    <%= button_to "I Super Promise that I have watched this Ad", reset_path, method: :delete %>
  </div>

<% else %>
  <% if flash[:success] %>
    <h2><%= flash[:success] %></h2>
  <% end %>

  <h1>You Have <%= 3 - session[:page_counter].to_i %> Views left </h1>

  <div class='show-container'>
    <p>Name: <%= @drink.name %></p>
    <p>Category: <%= @drink.category %></p>
    <p>Ounces: <%= @drink.ounces %></p>
    <marquee direction="right" scrollamount="20">
      <img class="show-img" src="<%= @drink.img_url %>" alt="<%= @drink.name%>">
    </marquee>


    <h2>Reviews</h2>
    <h5>Average Rating for <%= @drink.name %> | <%= @drink.rating_average %> </h5>
    <%# all review content  %>
      <%# - who wrote this review %>
    <% @drink.user_drinks.each do |user_drink| %>
      <p> <%= user_drink.content %> --- <%= user_drink.user.name %></p>
    <% end %>
  </div>
<% end %>

19-auth/paddys_puzzles/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaddysPuzzles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='nav'>
      <img class='logo' src="https://img.favpng.com/18/10/6/beer-irish-pub-bar-t-shirt-png-favpng-B1d28xyNdMZKeGpG1wY32B5nk.jpg" alt="barlogo">
    </div>

      <ul>
        <li><%= link_to 'User Home', users_path %></li>
        <li><%= link_to 'Drink Home', drinks_path %></li>
        <li><%= link_to 'New Drink', new_drink_path %></li>
        <% if @logged_in_user %>
          <li class='right'>Welcome <%= @logged_in_user.name %></li>
          <li class='right'><%= link_to 'Log-out', logout_path, method: :delete %></li>
        <% else %>
          <li class='right'><%= link_to 'Sign-up', new_user_path %></li>
          <li class='right'><%= link_to 'Log-in', new_login_path %></li>
        <% end %>
      </ul>


    <%= yield %>
  </body>
</html>

19-auth/paddys_puzzles/app/views/user_drinks/new.html.erb
<h1>Create</h1>

<%= form_for @user_drink do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :rating %>
  <%= f.number_field :rating %>

  <%= f.label :user_id %>
  <%= f.collection_select :user_id, @users, :id, :name %>

  <%= f.label :drink_id %>
  <%= f.collection_select :drink_id, @drinks, :id, :name  %>

  <%= f.submit %>
<% end %>

19-auth/paddys_puzzles/app/views/users/index.html.erb
<h1>Users</h1>

<div class="index_container">
  <% @users.each do |user| %>
    <div class="index_tile">
      <h3><%= link_to user.name, user %></h3>
      <img class="index_img" src="<%= user.img_url %>" alt="<%= user.name%>">
    </div>
  <% end %>
</div>

19-auth/paddys_puzzles/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.submit %>
<% end %>

19-auth/paddys_puzzles/app/views/users/show.html.erb
<h1>Drink</h1>

<div class='show-container'>
  <p>Name: <%= @user.name %></p>
  <marquee direction="right" scrollamount="20">
    <img class="show-img" src="<%= @user.img_url %>" alt="<%= @user.name%>">
  </marquee>

  <h2>My Drinks</h2>

  <% @user.drinks.uniq.each do |drink| %>
    <p><%= drink.name %> | <%= drink.rating_average %></p>
  <% end %>
</div>